### ISSUE TITLE
Install dependencies

### ISSUE THREAD

**Issue by NyakudyaA** [Mariosmsk/QChatGPT#1]
Problem

After installing the plugin the following error pops up
![pip2](https://user-images.githubusercontent.com/2510900/218713954-ee8dc869-d346-40b2-bdcc-d8715ab287ae.png)

# Solution
Please update metadata.txt to include an option that list dependencies needed for the plugin

**Comment by Gustry** [comment]
> Please update metadata.txt to include an option that list dependencies needed for the plugin

The line `plugin_dependencies` in `metadata.txt` is for other plugins.
https://docs.qgis.org/3.22/en/docs/pyqgis_developer_cookbook/plugins/plugins.html#plugin-metadata

> PIP-like comma separated list of other plugins to install, use plugin names coming from their metadata’s name field

There is now an error from QGIS plugin manager when clicking the install button : 

```
pyplugin_installer.instance().installPlugin('QChatGPT', stable=True)


Traceback (most recent call last):
  File "", line 1, in 
  File "/usr/share/qgis/python/pyplugin_installer/installer.py", line 333, in installPlugin
    self.processDependencies(plugin["id"])
  File "/usr/share/qgis/python/pyplugin_installer/installer.py", line 682, in processDependencies
    dlg = QgsPluginDependenciesDialog(plugin_id, to_install, to_upgrade, not_found)
  File "/usr/share/qgis/python/pyplugin_installer/qgsplugindependenciesdialog.py", line 92, in __init__
    _make_row(data, i, name)
  File "/usr/share/qgis/python/pyplugin_installer/qgsplugindependenciesdialog.py", line 63, in _make_row
    widget.use_stable_version = data['use_stable_version']
KeyError: 'use_stable_version'
```

**Comment by Mariosmsk** [comment]
Hi @Gustry, thanks for your issue. I missed it! I will go for a new version..
