### ISSUE TITLE
Error: No module named openai in Windows

### ISSUE THREAD

**Issue by Gajuan99** [Mariosmsk/QChatGPT#8]
Hi, when installing the plugin it asks me to install a series of packages, I accept the installation but it returns the error "ModuleNotFoundError: No module named 'openai'". I asked ChatGPT about the error and they told me to install the openai pip from cmd (pip install openai) but the problem persists. How can I solve it?

The more detailed the answer, the better. Thanks in advance.

![image](https://user-images.githubusercontent.com/121056026/220899972-ff3aa3a8-0908-4e38-9bf0-dbbdeb3e9149.png)

**Comment by waiotahi** [comment]
Likewise


Couldn't load plugin 'QChatGPT' due to an error when calling its classFactory() method 

ModuleNotFoundError: No module named 'openai' 
Traceback (most recent call last):
  File "C:\Users/simon/AppData/Roaming/QGIS/QGIS3\profiles\Lat37/python/plugins\QChatGPT\qchatqpt.py", line 45, in 
    import openai
  File "C:\PROGRA~1/QGIS32~3.0/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'openai'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\PROGRA~1/QGIS32~3.0/apps/qgis/./python\qgis\utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:\Users/simon/AppData/Roaming/QGIS/QGIS3\profiles\Lat37/python/plugins\QChatGPT\__init__.py", line 35, in classFactory
    from .qchatqpt import qchatgpt
  File "C:\PROGRA~1/QGIS32~3.0/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/simon/AppData/Roaming/QGIS/QGIS3\profiles\Lat37/python/plugins\QChatGPT\qchatqpt.py", line 51, in 
    import openai
  File "C:\PROGRA~1/QGIS32~3.0/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'openai'


Python version: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS version: 3.28.0-Firenze Firenze, ed3ad0430f3

**Comment by Einavg7** [comment]
Hello,

I have the same issue:

Couldn't load plugin 'QChatGPT' due to an error when calling its classFactory() method 

ModuleNotFoundError: No module named 'openai' 
Traceback (most recent call last):
  File "C:\Users/FFC-Notebook/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QChatGPT\qchatqpt.py", line 45, in 
    import openai
  File "C:\PROGRA~1/QGIS32~1.3/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'openai'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\PROGRA~1/QGIS32~1.3/apps/qgis/./python\qgis\utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:\Users/FFC-Notebook/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QChatGPT\__init__.py", line 35, in classFactory
    from .qchatqpt import qchatgpt
  File "C:\PROGRA~1/QGIS32~1.3/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/FFC-Notebook/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QChatGPT\qchatqpt.py", line 51, in 
    import openai
  File "C:\PROGRA~1/QGIS32~1.3/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'openai'


Python version: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS version: 3.28.3-Firenze Firenze, c12bcb2f76c

**Comment by shevelp** [comment]
Hi, @Einavg7 @waiotahi and @Gajuan99
The error you have is because you do not have the openai python library installed, open the terminal and install it using:

`pip install openai`

then reinstall the library and you should have no problem.

**Comment by rgc03** [comment]
And how can I solve this issue in QGIS under Windows 10 ?

**Comment by AndryZavala** [comment]
hello, When installing the plugin I get the following error **The following Python packages are required to use the plugin QChatGPT: pdfgpt**

and I can't install the packages using "pip install pdfgpt"
